### ISSUE TITLE
Problems with version 2.1.1

### ISSUE THREAD

**Issue by rdunn-Hypr** [markusbohl/fluent-ts-validator#6]
Hey there,

We've just picked up version 2.1.1 and now I have quite a few compiler errors. Now given the version increase was at a patch level, I would not have expected compiler errors. Happy if this expectation is wrong - just trying to understand if it's our implementation or not. We trip errors in this pattern `error TS2339: Property 'validate' does not exist on type <type>`

We are also trpping a `error TS2307: Cannot find module 'fluent-ts-validator'.` which cause an exception when running our tests.

Node 6.9.1
NPM 3.10.8
Typescript 2.4.1

If I revert to 2.1.0, everything works.

**Comment by markusbohl** [comment]
Uhm, strange. The [changes](https://github.com/markusbohl/fluent-ts-validator/commit/e12850aff0dcb88f6e4083e1a7c48322729a6044) I've made should not lead to a compiler error. Basically, it was only a (backwards compatible) enhancement in the return type of two methods in `AbstractValidator`.

After updating to 2.1.1, did you actually have the latest version in `node_modules`?

I'll try it with your versions of node, npm and typescript later that day.

**Comment by markusbohl** [comment]
I am such an idiot. I've published the wrong folder to npm with version `2.1.1`. Sorry for the inconvenience and thank you very much for bringing this issue up so fast.

Usually, I use an automated process for publishing. However, I did it manually with version `2.1.1` since I "thought" to have a problem with the build pipeline. (Which I didn't).

Would you be so kind to check if the newly (automatically) published version [2.1.2](https://github.com/markusbohl/fluent-ts-validator/releases/tag/2.1.2) works as expected?

Thanks again.

**Comment by rdunn-Hypr** [comment]
Hey thanks! We really appreciate how fast you got on to this. This is awesome. I'll get on to testing it right now

**Comment by rdunn-Hypr** [comment]
Hey @markusbohl 

Awesome, we are good to go. Thanks for getting on to this so fast - love your MTTR!

**Comment by markusbohl** [comment]
Nice. Thanks. Closing this issue.
